name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ "development" ] # Pipeline berjalan otomatis saat ada push ke branch development

jobs:
  build-and-test:
    name: Continuous Integration (CI)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3

    - name: Setup Node.js Environment
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: echo "Mengonfigurasi dan menginstal dependensi aplikasi..."

    - name: Run Unit Test
      run: echo "Menjalankan unit test otomatis... Semua tes berhasil dilewati!"

  deploy-to-staging:
    name: Continuous Delivery (CD)
    needs: build-and-test # TAHAP CD HANYA BERJALAN JIKA TAHAP CI SELESAI & SUKSES
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      run: |
        echo "Mengautentikasi koneksi aman ke AWS Cloud Provider..."
        echo "AWS_ACCESS_KEY_ID terverifikasi."
        echo "AWS_SECRET_ACCESS_KEY terverifikasi."

    - name: Deploy Application to AWS Staging Server
      run: |
        echo "Mempersiapkan server staging AWS EC2 Instance..."
        echo "Menarik Docker image terbaru dari registry..."
        echo "Aplikasi berhasil di-deploy secara otomatis ke lingkungan Staging AWS!"